---
# this playbook runs bin/zowe-setup-certificates.sh to setup certificates for Zowe
# FIXME: HOSTNAME should be combination of zowe_zos_host and zowe_external_domain_name.
#        The reason we use zowe_zos_host here is the certificates created here will only
#        be used by z/OS side. Docker image may use different certificate with it's
#        own zowe-setup-certificates.sh
- name: Prepare zowe-setup-certificates.env
  raw: >-
    cat "{{ zowe_root_dir }}/bin/zowe-setup-certificates.env" | \
    sed -e "s+^HOSTNAME=.*\$+HOSTNAME={{ zowe_zos_host }}+" | \
    sed -e "s+^IPADDRESS=.*\$+IPADDRESS={{ zowe_external_ip_address }}+" | \
    sed -e "s+^ZOSMF_CERTIFICATE=.*\$+ZOSMF_CERTIFICATE={{ zowe_zosmf_certificate }}+" | \
    sed -e "s+^EXTERNAL_CERTIFICATE=.*\$+EXTERNAL_CERTIFICATE={{ zowe_external_certficate }}+" | \
    sed -e "s+^EXTERNAL_CERTIFICATE_ALIAS=.*\$+EXTERNAL_CERTIFICATE_ALIAS={{ zowe_external_certficate_alias }}+" | \
    sed -e "s+^EXTERNAL_CERTIFICATE_AUTHORITIES=.*\$+EXTERNAL_CERTIFICATE_AUTHORITIES={{ zowe_external_certficate_authorities }}+" | \
    sed -e "s+^VERIFY_CERTIFICATES=.*\$+VERIFY_CERTIFICATES={{ zowe_apiml_verify_certficates_of_services|string|lower }}+" | \
    sed -e "s+^KEYSTORE_DIRECTORY=.*\$+KEYSTORE_DIRECTORY={{ zowe_keystore_dir }}+" | \
    sed -e "s+^KEYSTORE_PASSWORD=.*\$+KEYSTORE_PASSWORD={{ zowe_keystore_password }}+" | \
    sed -e "s+^KEYSTORE_ALIAS=.*\$+KEYSTORE_ALIAS={{ zowe_keystore_alias }}+" | \
    sed -e "s+^ZOWE_USER_ID=.*\$+ZOWE_USER_ID={{ zowe_runtime_user }}+" | \
    sed -e "s+^ZOWE_GROUP_ID=.*\$+ZOWE_GROUP_ID={{ zowe_runtime_group }}+" \
    > "{{ work_dir_remote }}/zowe-setup-certificates.env"

- name: Show zowe-setup-certificates.env
  raw: cat "{{ work_dir_remote }}/zowe-setup-certificates.env"

- name: Setup certificates
  import_role:
    name: zos
    tasks_from: run_script
  vars:
    script_chdir: "{{ zowe_root_dir }}/bin"
    script_filename: ./zowe-setup-certificates.sh
    script_parameters: "-p \"{{ work_dir_remote }}/zowe-setup-certificates.env\""

- name: List certifactes directory
  raw: ls -l "{{ zowe_keystore_dir }}"
