---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discovery
  namespace: zowe
  labels:
    app.kubernetes.io/name: zowe
    app.kubernetes.io/instance: zowe
    app.kubernetes.io/version: "2.1.0"
    app.kubernetes.io/component: discovery
    app.kubernetes.io/part-of: apiml
    app.kubernetes.io/managed-by: manual
spec:
  serviceName: discovery-service
  selector:
    matchLabels:
      app.kubernetes.io/name: zowe
      app.kubernetes.io/instance: zowe
      app.kubernetes.io/component: discovery
  # FIXME: please match this with ZWE_DISCOVERY_SERVICES_REPLICAS defined in ConfigMap zowe-config zowe.yaml section
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zowe
        app.kubernetes.io/instance: zowe
        app.kubernetes.io/component: discovery
    spec:
      securityContext:
        runAsUser: 20000
        runAsGroup: 20000
        fsGroup: 20000
        runAsNonRoot: true
      serviceAccountName: zowe-sa
      volumes:
        - name: tmp
          emptyDir: {}
        - name: zowe-runtime
          emptyDir: {}
        - name: zowe-config
          configMap:
            name: zowe-config
        - name: zowe-keystore
          projected:
            sources:
              - secret:
                  name: zowe-certificates-secret
        - name: zowe-logs
          emptyDir: {}
        - name: zowe-workspace
          persistentVolumeClaim:
            claimName: zowe-workspace-pvc
      containers:
        - name: discovery
          image: zowe-docker-snapshot.jfrog.io/ompzowe/discovery-service:2.1.1-SNAPSHOT-ubuntu.v2-x-x
          imagePullPolicy: Always
          resources:
            requests:
              memory: "384Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "800m"
          ports:
            - name: discovery-port
              containerPort: 7553
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: 7553
            # this should give 90 * periodSeconds(default to 10) seconds about 15 minutes to confirm it's ready
            periodSeconds: 10
            failureThreshold: 90
          livenessProbe:
            tcpSocket:
              port: 7553
            # this should give 3 * periodSeconds(default to 10) seconds about 30 seconds to confirm it's offline
            periodSeconds: 10
            failureThreshold: 3
          command: ["/bin/bash", "-c"]
          args:
            - "/home/zowe/runtime/bin/zwe internal start -c /home/zowe/instance/zowe.yaml"
          env:
            - name: ZWE_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CMMN_LB
              value: apiml-common-lib/bin/api-layer-lite-lib-all.jar
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/home/zowe/runtime/bin/zwe internal container prestop -c /home/zowe/instance/zowe.yaml"]
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            capabilities:
              drop:
                - all
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: zowe-runtime
              mountPath: "/home/zowe/runtime"
            - name: zowe-config
              mountPath: "/home/zowe/instance/zowe.yaml"
              subPath: zowe.yaml
              readOnly: true
            - name: zowe-keystore
              mountPath: "/home/zowe/keystore"
              readOnly: true
            - name: zowe-logs
              mountPath: "/home/zowe/instance/logs"
            - name: zowe-workspace
              mountPath: "/home/zowe/instance/workspace"
      initContainers:
        - name: init-zowe
          image: zowe-docker-snapshot.jfrog.io/ompzowe/zowe-launch-scripts:2.1.0-ubuntu.v2-x-staging
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            capabilities:
              drop:
                - all
          volumeMounts:
            - name: tmp
              mountPath: "/tmp"
            - name: zowe-runtime
              mountPath: "/home/zowe/runtime"
            - name: zowe-workspace
              mountPath: "/home/zowe/instance/workspace"
