---
apiVersion: batch/v1
kind: Job
metadata:
  name: explorer-ip
  namespace: zowe
  labels:
    app.kubernetes.io/name: zowe
    app.kubernetes.io/instance: zowe
    app.kubernetes.io/version: "3.0.0"
    app.kubernetes.io/component: job-explorer-ip
    app.kubernetes.io/managed-by: manual
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zowe
        app.kubernetes.io/instance: zowe
        app.kubernetes.io/component: explorer-ip
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsUser: 20000
        runAsGroup: 20000
        fsGroup: 20000
        runAsNonRoot: true
      serviceAccountName: zowe-sa
      volumes:
        - name: tmp
          emptyDir: {}
        - name: zowe-runtime
          emptyDir: {}
        - name: zowe-config
          configMap:
            name: zowe-config
        - name: zowe-keystore
          projected:
            sources:
              - secret:
                  name: zowe-certificates-secret
        - name: zowe-logs
          emptyDir: {}
        - name: zowe-workspace
          persistentVolumeClaim:
            claimName: zowe-workspace-pvc
      containers:
        - name: explorer-ip
          image: zowe-docker-snapshot.jfrog.io/ompzowe/explorer-ip:3.0.1-ubuntu.v3-x-master
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          command: ["/bin/bash", "-c"]
          args:
            - "/home/zowe/runtime/bin/zwe internal start -c /home/zowe/instance/zowe.yaml"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/home/zowe/runtime/bin/zwe internal container prestop -c /home/zowe/instance/zowe.yaml"]
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            capabilities:
              drop:
                - all
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: zowe-runtime
              mountPath: "/home/zowe/runtime"
            - name: zowe-config
              mountPath: "/home/zowe/instance/zowe.yaml"
              subPath: zowe.yaml
              readOnly: true
            - name: zowe-keystore
              mountPath: "/home/zowe/keystore"
              readOnly: true
            - name: zowe-logs
              mountPath: "/home/zowe/instance/logs"
            - name: zowe-workspace
              mountPath: "/home/zowe/instance/workspace"
      initContainers:
        - name: init-zowe
          image: zowe-docker-snapshot.jfrog.io/ompzowe/zowe-launch-scripts:3.0.0-ubuntu.v3-x-staging
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            capabilities:
              drop:
                - all
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: zowe-runtime
              mountPath: "/home/zowe/runtime"
            - name: zowe-workspace
              mountPath: "/home/zowe/instance/workspace"
