version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      all-version-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
      all-security-minorpatch:
        applies-to: security-updates  
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
