---
- name: start docker in detached mode
  raw: >- 
    docker run -d --rm --env ZOWE_EXPLORER_HOST={{ zowe_external_domain_name }} \
      --env ZOWE_IP_ADDRESS=0.0.0.0 \
      --env ZOSMF_HOST={{zos_zosmf_host}} \
      --env ZOSMF_PORT={{zos_zosmf_port}} \
      --env ZWED_agent_host={{zowe_zos_host}} \
      --env ZWED_agent_https_port={{zowe_zss_port}} \
      --env ZOWE_ZLUX_TELNET_PORT={{zowe_zlux_terminal_telnet_port}} \
      --env ZOWE_ZLUX_SECURITY_TYPE={{ zowe_zlux_terminal_telnet_security_type }} \
      --env ZOWE_ZLUX_SSH_HOST={{zowe_zos_host}} \
      --env GATEWAY_PORT={{zowe_apiml_gateway_port}} \
      --expose {{zowe_apiml_gateway_port}} \
      -p {{zowe_apiml_discovery_port}}:7553 \
      -p {{zowe_apiml_gateway_port}}:{{zowe_apiml_gateway_port}} \
      -p {{zowe_zlux_port}}:8544 \
      {{zowe_docker_image}}:{{zowe_docker_tag}}
  register: container_id_response
  delegate_to: localhost

- name: Set container_id
  set_fact:
    container_id: "{{ container_id_response.stdout_lines[0] }}"

# wait for docker to start
- import_role:
    name: docker
    tasks_from: wait-for-docker

# get docker logs
- import_role:
    name: docker
    tasks_from: docker-logs
