---
# This playbook runs the api generation test on Zowe

# ============================================================================
# validate variables
- import_role:
    name: common
    tasks_from: validate_variables
  vars:
    variable_list:
    - zowe_api_gen_dir
    - zowe_root_dir
    - zowe_instance_dir
    - zos_zosmf_port
    - zowe_proclib_membername
    - zowe_job_prefix
    - zowe_zlux_port
    - zowe_apiml_gateway_port

# ============================================================================
- name: Delete old reports
  file:
    path: "{{ work_dir_local }}/{{ inventory_hostname }}/reports"
    state: absent
  delegate_to: localhost

# ============================================================================
- name: Prepare api gen test folder
  command: npm install --no-audit
  args:
    chdir: "{{ zowe_api_gen_dir }}"
  delegate_to: localhost

# ============================================================================
- name: capture API information
  command: npm test {{ zowe_api_generation_testcases  }}
  args:
    chdir: "{{ zowe_api_gen_dir }}"
  environment:
    ZOWE_ROOT_DIR: "{{ zowe_root_dir }}"
    ZOWE_INSTANCE_DIR: "{{ zowe_instance_dir }}"
    SSH_HOST: "{{ ansible_ssh_host }}"
    SSH_PORT: "{{ ansible_port }}"
    SSH_USER: "{{ ansible_user }}"
    SSH_PASSWD: "{{ ansible_password }}"
    ZOSMF_PORT: "{{ zos_zosmf_port }}"
    ZOWE_DS_MEMBER: "{{ zowe_proclib_membername }}"
    ZOWE_JOB_PREFIX: "{{ zowe_job_prefix }}"
    ZOWE_ZLUX_HTTPS_PORT: "{{ zowe_zlux_port }}"
    ZOWE_API_MEDIATION_GATEWAY_HTTP_PORT: "{{ zowe_apiml_gateway_port }}"
    DEBUG: "{{ zowe_api_gen_debug_mode | default('') }}"
  delegate_to: localhost
