apiVersion: v1
kind: ServiceAccount
metadata:
  name: zowe-sa
  namespace: zowe
  labels:
    app.kubernetes.io/name: zowe
    app.kubernetes.io/instance: zowe
    app.kubernetes.io/managed-by: manual
automountServiceAccountToken: false
