---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: files-api-hpa
  namespace: zowe
  labels:
    app.kubernetes.io/name: zowe
    app.kubernetes.io/instance: zowe
    app.kubernetes.io/version: "1.25.0"
    app.kubernetes.io/component: hpa
    app.kubernetes.io/managed-by: manual
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: files-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
