# zowe_setup_jcl_enable
# Label: Enable JCL Samples for Zowe Setup
# Abstract: Enable setup via generated JCL samples, or disable to automate via the legacy zwe Unix CLI.
# Category: zowe
# Description:
#  Set this to true to have the workflow automatically generate and use JCL samples for the configuration steps. If set to false, the workflow will instead automate setup directly using legacy `zwe` operations (the Unix CLI tool). Note: If you set this to false, you do not need to fill out the JCL header information in the next field.
zowe_setup_jcl_enable=true

# zowe_setup_jcl_header
# Label: JCL Configuration Positional JOB Parameters and Keywords
# Abstract: Optional JOB statement parameters used only for Zowe configuration by JCL samples.
# Category: zowe
# Description:
#  These parameters and keywords are optional, and by default empty. These are used separately from z/OSMF defined JOB cards. Each line should be less than 70 characters, omit start-of-line identifier statements such as "//", "/*", and include commas for end-of-line continuation.
zowe_setup_jcl_header=

# zowe_setup_dataset_prefix
# Label: Target Zone Prefix of Zowe setup MVS datasets
# Abstract: MVS dataset prefix for Zowe runtime libraries used during installation and initialization.
# Category: zowe
# Description:
#  The Target Zone Prefix for MVS datasets where Zowe runtime libraries (SZWEAUTH, SZWESAMP, SZWEEXEC, and SZWELOAD) are created during the install step. Zowe also relies on this prefix to locate ZWEGENER and sample libraries when executing `zwe init` commands with JCL.
zowe_setup_dataset_prefix=IBMUSER.ZWEV3

# zowe_setup_dataset_proclib
# Label: Zowe setup MVS procedure library
# Abstract: Where Zowe STCs will be copied over
# Category: zowe
# Description:
#  Where Zowe STCs will be copied over
zowe_setup_dataset_proclib=USER.PROCLIB

# zowe_setup_dataset_parmlib
# Label: Zowe setup MVS parameter library
# Abstract: Zowe PARMLIB
# Category: zowe
# Description:
#  Zowe parameter library
zowe_setup_dataset_parmlib=IBMUSER.ZWEV3.CUST.PARMLIB

# zowe_setup_dataset_parmlibMembers_zis
# Label: Zowe setup PARMLIB members for ZIS plugins
# Abstract: Zowe ZIS plugins PARMLIB
# Category: zowe
# Description:
#  Holds PARMLIB members for ZIS plugins
zowe_setup_dataset_parmlibMembers_zis=ZWESIP00

# zowe_setup_dataset_jcllib
# Label: Zowe setup MVS JCL library
# Abstract: JCL library where Zowe will store temporary JCLs during initialization
# Category: zowe
# Description:
#  JCL library where Zowe will store temporary JCLs during initialization
zowe_setup_dataset_jcllib=IBMUSER.ZWEV3.CUST.JCLLIB

# zowe_setup_dataset_loadlib
# Label: Zowe setup Utilities and extensions library
# Abstract: Load library where Zowe stores libraries for Utilities for use by Zowe and extensions
# Category: zowe
# Description:
#  Load library for Utilities for use by Zowe and extensions
zowe_setup_dataset_loadlib=IBMUSER.ZWEV3.SZWELOAD

# zowe_setup_dataset_authLoadlib
# Label: Zowe setup MVS auth load library
# Abstract: APF authorized LOADLIB for Zowe
# Category: zowe
# Description:
#  APF authorized LOADLIB for Zowe core
zowe_setup_dataset_authLoadlib=IBMUSER.ZWEV3.SZWEAUTH

# zowe_setup_dataset_authPluginLib
# Label: Zowe setup MVS auth plugin library
# Abstract: APF authorized LOADLIB for Zowe ZIS Plugins
# Category: zowe
# Description:
#  APF authorized LOADLIB for Zowe ZIS Plugins
zowe_setup_dataset_authPluginLib=IBMUSER.ZWEV3.CUST.ZWESAPL

# zowe_runtimeDirectory
# Label: Existing Zowe runtime directory
# Abstract: Zowe runtime (root) directory with libraries
# Category: zowe
# Description:
#  Existing Zowe runtime.<br />
#  If you created ZOWE via PSWI, <br />
#  zowe runtime is your Target Mount Point from PSWI deployment. <br />
#  It is used by ZWESLSTC or by zwe command
zowe_runtimeDirectory=

# zowe_logDirectory
# Label: Zowe log directory
# Abstract: Where to store runtime logs
# Category: zowe
# Description:
#  Where to store runtime logs
zowe_logDirectory=/global/zowe/logs

# zowe_workspaceDirectory
# Label: Zowe workspace directory
# Abstract: Zowe runtime workspace directory
# Category: zowe
# Description:
#  Zowe runtime workspace directory
zowe_workspaceDirectory=/global/zowe/workspace

# zowe_extensionDirectory
# Label: Where extensions are installed
# Abstract: Where extensions are installed
# Category: zowe
# Description:
#  zowe_extensionDirectory
zowe_extensionDirectory=/global/zowe/extensions

# zowe_job_name
# Label: Zowe job name
# Abstract: Zowe JES job name
# Category: zowe
# Description:
#  Zowe JES job name
zowe_job_name=ZWE1SV

# zowe_job_prefix
# Label: Zowe job prefix
# Abstract: Prefix of component address space
# Category: zowe
# Description:
#  Prefix of component address space
zowe_job_prefix=ZWE1

# zowe_externalDomains
# Label: Zowe external domains
# Abstract: The list of external domains
# Category: zowe
# Description:
#  Defines a list of external domains that will be used by the Zowe instance.
zowe_externalDomains=example.com

# zowe_externalPort
# Label: Zowe external port
# Abstract: The port you use to access Zowe Gateway from your web browser
# Category: zowe
# Description:
#  This is the port you use to access Zowe Gateway from your web browser.
#  In many use cases, this should be same as <b>components.gateway.port</b>. But in
#  some use cases, like containerization, this port could be different.
zowe_externalPort=7554

# zowe_launchScript_logLevel
# Label: Zowe launch script logLevel
# Abstract: Set to "debug" or "trace" to display extra debug information
# Category: zowe
# Description:
#  Set to "debug" or "trace" to display extra debug information
# Choices: info,debug,trace
zowe_launchScript_logLevel=info

# zowe_launchScript_onComponentConfigureFail
# Label: Zowe launch script component configuration
# Abstract: Set to "exit" or "warn" if any component has an error
# Category: zowe
# Description:
#  Set to "exit" if you want startup to exit if any component has an error in the configuration stage, otherwise zwe will issue a warning but continue running.
# Choices: warn,exit
zowe_launchScript_onComponentConfigureFail=warn

# zowe_network_server_tls_attls
# Label: Application Transparent Transport Layer Security for inbound
# Abstract: Enable on AT-TLS on inbound calls (server)
# Category: network
# Description:
#  Enable aware mode of inbound AT-TLS rules of all Zowe components.
zowe_network_server_tls_attls=false

# zowe_network_client_tls_attls
# Label: Application Transparent Transport Layer Security for outbound
# Abstract: Enable on AT-TLS on outbound calls (client)
# Category: network
# Description:
#  Enable aware mode of outbound AT-TLS rules of all Zowe components.
zowe_network_client_tls_attls=false

# zowe_network_server_tls_minTls
# Label: Transport Layer Security - min version
# Abstract: TLS minimum version
# Category: network
# Description:
#  The default configuration of the minimal version of a security transport protocol for inbound calls.
#  TLS settings only apply when attls=false.
#  Else you must use AT-TLS configuration for TLS customization.
#  
# Choices: TLSv1.1,TLSv1.2,TLSv1.3
zowe_network_server_tls_minTls=TLSv1.2

# zowe_network_server_tls_maxTls
# Label: Transport Layer Security - max version
# Abstract: TLS maximum version
# Category: network
# Description:
#  The default configuration of the maximum version of a security transport protocol for inbound calls.
#  TLS settings only apply when attls=false.
#  Else you must use AT-TLS configuration for TLS customization.
#  
# Choices: TLSv1.1,TLSv1.2,TLSv1.3
zowe_network_server_tls_maxTls=TLSv1.3

# zowe_network_allowedDomains
# Label: Zowe allowed domains
# Abstract: The list of allowed domains in services that register to the API ML Discovery Service
# Category: network
# Description:
#  Defines a list of domains that can be used by the Zowe instance.
zowe_network_allowedDomains=www.example.com

# zowe_certificate_keystore_type
# Label: Zowe certificate keystore type
# Abstract: Certificate keystore type (PKCS12, JCERACFKS)
# Category: certificates
# Description:
#  Certificate keystore type (PKCS12, JCERACFKS)
# Choices: PKCS12,JCERACFKS
zowe_certificate_keystore_type=JCERACFKS

# zowe_certificate_keystore_file
# Label: Zowe certificate keystore file
# Abstract: Zowe certificate keystore file. For keyring, the format is "safkeyring://OWNER/KEYRING".
# Category: certificates
# Description:
#  Zowe certificate keystore file
zowe_certificate_keystore_file=safkeyring://OWNER/KEYRING

# zowe_certificate_keystore_password
# Label: Zowe certificate keystore password
# Abstract: Certificate keystore password.
# Category: certificates
# Description:
#  Certificate keystore password.
zowe_certificate_keystore_password=password

# zowe_certificate_keystore_alias
# Label: Zowe certificate keystore alias
# Abstract: Alias for the certificate keystore
# Category: certificates
# Description:
#  Alias for the certificate keystore
zowe_certificate_keystore_alias=localhost

# zowe_certificate_truststore_type
# Label: Zowe certificate truststore type
# Abstract: Zowe certificate truststore type
# Category: certificates
# Description:
#  Zowe certificate truststore type
# Choices: PKCS12,JCERACFKS
zowe_certificate_truststore_type=JCERACFKS

# zowe_certificate_truststore_file
# Label: Zowe certificate truststore file
# Abstract: File location for certificate truststore. For keyring, the format is "safkeyring://OWNER/KEYRING"
# Category: certificates
# Description:
#  File location for the certificate truststore
zowe_certificate_truststore_file=safkeyring://OWNER/KEYRING

# zowe_certificate_truststore_password
# Label: Zowe certificate truststore password
# Abstract: Password for the certificate truststore
# Category: certificates
# Description:
#  Password for the certificate truststore
zowe_certificate_truststore_password=password

# java_home
# Label: JAVA home
# Abstract: Path to the JAVA home
# Category: java
# Description:
#  Path to the JAVA home
java_home=

# node_home
# Label: Node.js home
# Abstract: Path to the Node.js home
# Category: Node.js
# Description:
#  Path to the Node.js home
node_home=

# zOSMF_host
# Label: z/OSMF host
# Abstract: Hostname of the running z/OSMF instance
# Category: zOSMF
# Description:
#  Hostname of the running z/OSMF instance
zOSMF_host=dvipa.example.com

# zOSMF_port
# Label: z/OSMF port
# Abstract: Port of the z/OSMF instance
# Category: zOSMF
# Description:
#  Port of the z/OSMF instance
zOSMF_port=443

# zOSMF_applId
# Label: z/OSMF APPLID
# Abstract: APPLID of the z/OSMF instance
# Category: zOSMF
# Description:
#  APPLID of the z/OSMF instance
zOSMF_applId=IZUDFLT

# components_gateway_port
# Label: Gateway port
# Abstract: Port for API ML Gateway
# Category: components
# Description:
#  Port for API ML Gateway
components_gateway_port=7554

# components_zaas_port
# Label: ZAAS port
# Abstract: Port for API ML ZAAS
# Category: components
# Description:
#  Port for API ML ZAAS
components_zaas_port=7558

# components_api_catalog_port
# Label: API catalog port
# Abstract: Port on which API Catalog should be running.
# Category: components
# Description:
#  Port on which API Catalog should be running.
components_api_catalog_port=7552

# components_discovery_port
# Label: Discovery port
# Abstract: Port on which Discovery service should be running
# Category: components
# Description:
#  Port on which Discovery service should be running
components_discovery_port=7553

# components_caching_service_port
# Label: Caching service port
# Abstract: Port for Caching service
# Category: components
# Description:
#  Port for Caching service
components_caching_service_port=7555

# components_caching_service_storage_infinispan_jgroups_port
# Label: Caching service storage jgroups port
# Abstract: Port for jgroups
# Category: components
# Description:
#  Port for jgroups. This is required if storage mode is infinispan.
components_caching_service_storage_infinispan_jgroups_port=7559

# components_caching_service_storage_infinispan_jgroups_keyExchange_port
# Label: Caching service storage jgroups keyExchange port
# Abstract: Port for jgroups key exchange
# Category: components
# Description:
#  Port for jgroups key exchange. This is required if storage mode is infinispan.
components_caching_service_storage_infinispan_jgroups_keyExchange_port=7560

# zowe_rbacProfileIdentifier
# Label: Zowe Profile Identifier
# Abstract: ID you use to separate multiple Zowe installs
# Category: zowe
# Description:
#  ID when determining resource names used in RBAC authorization checks such as dataservices with RBAC expects this ID in SAF resources
zowe_rbacProfileIdentifier=1

# zowe_cookieIdentifier
# Label: Zowe Cookie Identifier
# Abstract: ID that can be used by servers to distinguish their cookies from unrelated Zowe installs
# Category: zowe
# Description:
#  ID which allows multiple copies of Zowe to be used within the same client
zowe_cookieIdentifier=1

# zowe_setup_security_product
# Label: Security product name
# Abstract: Security product name. Can be RACF, ACF2 or TSS
# Category: security
# Description:
#  Security product name. Can be RACF, ACF2 or TSS
# Choices: RACF,TSS,ACF2
zowe_setup_security_product=RACF

# zowe_setup_security_groups_admin
# Label: Zowe admin user group
# Abstract: Zowe admin user group
# Category: security
# Description:
#  Zowe admin user group
zowe_setup_security_groups_admin=ZWEADMIN

# zowe_setup_security_groups_stc
# Label: Zowe STC group
# Abstract: Zowe STC group
# Category: security
# Description:
#  Zowe STC group
zowe_setup_security_groups_stc=ZWEADMIN

# zowe_setup_security_groups_sysProg
# Label: Zowe SysProg group
# Abstract: Zowe SysProg group
# Category: security
# Description:
#  Zowe SysProg group
zowe_setup_security_groups_sysProg=ZWEADMIN

# zowe_setup_security_users_zowe
# Label: Zowe runtime user
# Abstract: Zowe runtime user name of main service
# Category: security
# Description:
#  Zowe runtime user name of main service
zowe_setup_security_users_zowe=ZWESVUSR

# zowe_setup_security_users_zis
# Label: Zowe runtime user name of ZIS
# Abstract: Zowe runtime user name of ZIS
# Category: security
# Description:
#  Zowe runtime user name of ZIS
zowe_setup_security_users_zis=ZWESIUSR

# zowe_setup_security_stcs_zowe
# Label: STC name
# Abstract: STC name of main service
# Category: security
# Description:
#  STC name of main service
zowe_setup_security_stcs_zowe=ZWESLSTC

# zowe_setup_security_stcs_zis
# Label: STC name of ZIS
# Abstract: STC name of ZIS
# Category: security
# Description:
#  STC name of ZIS
zowe_setup_security_stcs_zis=ZWESISTC

# zowe_setup_security_stcs_aux
# Label: STC name of Auxiliary Service
# Abstract: STC name of Auxiliary Service
# Category: security
# Description:
#  STC name of Auxiliary Service
zowe_setup_security_stcs_aux=ZWESASTC