---
# ==============================================================================
# Constants
# ==============================================================================

# ==============================================================================
# Variables should be verified and overwrittern.
# ==============================================================================
# temporary folder on remote
work_dir_remote:
# default zowe runtime root directory
zowe_root_dir: ~/zowe
# dataset prefix where zowe will be installed
zowe_dataset_prefix:
# instanceDir
zowe_instance_dir: ~/.zowe/instance
# zowe job prefix.
zowe_job_prefix: ZWE
# instance id. This will be put into zowe job name after {{ zowe_job_prefix }}
zowe_instance_id: 1
# default z/OSMF port. Optional, default value is ansible_ssh_host
zos_zosmf_host:
# default z/OSMF port
zos_zosmf_port: 10443
# APIML ports
zowe_apiml_catalog_port: 7552
zowe_apiml_discovery_port: 7553
zowe_apiml_gateway_port: 7554
zowe_apiml_verify_certficates_of_services: true
# explorer APIs/plugins ports
zowe_jobs_api_port: 8545
zowe_mvs_api_port: 8547
zowe_jobs_explorer_port: 8546
zowe_mvs_explorer_port: 8548
zowe_uss_explorer_port: 8550
# zlux ports
zowe_zlux_port: 8544
zowe_zss_https: True
zowe_zss_port: 8542
# make sure that this equals to zssCrossMemoryServerName in install in zowe-install-apf-server.yaml
zowe_zss_xmem_name: ZWESIS_STD
zowe_zlux_terminal_ssh_port: 22
zowe_zlux_terminal_telnet_port: 23
# The security type of the tn3270 connection - valid values are blank('') for telnet, or 'tls'
zowe_zlux_terminal_telnet_security_type:
zowe_zosmf_certificate:
zowe_external_certficate:
zowe_external_certficate_alias:
zowe_external_certficate_authorities:
zowe_keystore_dir: ~/.zowe/keystore
zowe_keystore_password: password
zowe_keystore_alias: localhost
zowe_keyring_certname: ZoweCert
zowe_proclib_dsname: auto
zowe_proclib_membername: ZWESVSTC
zowe_runtime_user: ZWESVUSR
zowe_runtime_group: ZWEADMIN
zowe_auto_create_user_group: false
# if we want to skip executing ZWESECUR job
zowe_configure_skip_zwesecur: false

################################################################################
# these are default variables for cross memory configuration
zowe_xmem_proclib:
zowe_xmem_parmlib:
# this variable is deprecated in favor of zowe_dataset_prefix
zowe_xmem_loadlib:
zowe_xmem_proclib_member_zss: ZWESISTC
zowe_xmem_proclib_member_aux: ZWESASTC
zowe_xmem_stc_user: ZWESIUSR
zowe_xmem_stc_group: ZWEADMIN

# optional, default to ansible_ssh_host
# required for zD&T (external IP is different from internal IP)
zowe_zos_host:
# optional, default to zowe_zos_host
# for z/OS deployment, this can be left empty and be same as zowe_zos_host
# for all-in-one docker deployment, this can be set to domain where you start docker container
zowe_external_domain_name:
# optional, no default value
# required for zD&T (external IP is different from internal IP)
zowe_external_ip_address:

# property added to instance.env for extender test - Note this variable is for PTF installation verification purpose, not used by any extensions. You are safe to ignore.
zowe_extender_test_property: EXAMPLE_EXTENDER_PROPERTY=TEST123
