---
# ============================================================================
- name: Update zowe_test_user from ansible_user if it's not defined
  # hide log to avoid exposing zowe_test_user
  no_log: True
  set_fact:
    zowe_test_user: "{{ hostvars[inventory_hostname].ansible_user }}"
  when: zowe_test_user == '' or zowe_test_user is none

- name: Update zowe_test_password from ansible_password if it's not defined
  # hide log to avoid exposing zowe_test_password
  no_log: True
  set_fact:
    zowe_test_password: "{{ hostvars[inventory_hostname].ansible_password }}"
  when: zowe_test_password == '' or zowe_test_password is none

# ============================================================================
# verify variables
- import_role:
    name: common
    tasks_from: validate_variables
  vars:
    variable_list:
    - zowe_zos_host
    - zowe_external_domain_name
    #- zowe_zss_port
    - zowe_zlux_port
    - zowe_jobs_api_port
    - zowe_apiml_gateway_port

- name: Check if zowe_test_user has a value
  fail:
    msg: zowe_test_user is required
  when: zowe_test_user is not defined or zowe_test_user is none or zowe_test_user == ''
  # hide log to avoid exposing zowe_test_user
  no_log: True

- name: Check if zowe_test_password has a value
  fail:
    msg: zowe_test_password is required
  when: zowe_test_password is not defined or zowe_test_password is none or zowe_test_password == ''
  # hide log to avoid exposing zowe_test_password
  no_log: True

# ============================================================================
# Wait for Zowe services be started

- name: Wait for APIML port {{ zowe_apiml_gateway_port }} to be available
  uri:
    url: "https://{{ zowe_zos_host }}:{{ zowe_apiml_gateway_port }}"
    follow_redirects: none
    method: GET
    validate_certs: false
  register: _result
  until: _result.status == 200
  retries: "{{ wait_for_zowe_service_retries | int }}"
  delay: "{{ wait_for_zowe_service_delay | int }}"
  # if zowe_zos_host and zowe_external_domain_name are not same, zlux could be
  # started off z/OS and then we couldn't test right now
  when: zowe_zos_host == zowe_external_domain_name and (zowe_launch_components is none or zowe_launch_components == "" or "gateway" in zowe_launch_components)
  delegate_to: localhost

- name: Wait for being able to login to API Catalog
  uri:
    url: "https://{{ zowe_zos_host }}:{{ zowe_apiml_gateway_port }}/apicatalog/api/v1/auth/login"
    follow_redirects: none
    method: POST
    body_format: json
    body: 
      username: "{{ zowe_test_user }}"
      password: "{{ zowe_test_password }}"
    validate_certs: false
    status_code:
    - 200
    - 204
  register: _result
  until: _result.status == 204
  retries: "{{ wait_for_zowe_service_retries | int }}"
  delay: "{{ wait_for_zowe_service_delay | int }}"
  # if zowe_zos_host and zowe_external_domain_name are not same, zlux could be
  # started off z/OS and then we couldn't test right now
  when: zowe_zos_host == zowe_external_domain_name and (zowe_launch_components is none or zowe_launch_components == "" or "api-catalog" in zowe_launch_components)
  delegate_to: localhost
  # hide log to avoid exposing zowe_test_user and zowe_test_password
  no_log: True

- name: Wait for Jobs API port {{ zowe_jobs_api_port }} to be available
  uri:
    url: "https://{{ zowe_zos_host }}:{{ zowe_jobs_api_port }}/jobs/api/v1?prefix=ZWE*&status=ACTIVE"
    url_password: "{{ zowe_test_password }}"
    url_username: "{{ zowe_test_user }}"
    follow_redirects: none
    method: GET
    validate_certs: false
  register: _result
  until: _result.status == 200
  retries: "{{ wait_for_zowe_service_retries | int }}"
  delay: "{{ wait_for_zowe_service_delay | int }}"
  # if zowe_zos_host and zowe_external_domain_name are not same, zlux could be
  # started off z/OS and then we couldn't test right now
  when: zowe_zos_host == zowe_external_domain_name and (zowe_launch_components is not none and "jobs-api" in zowe_launch_components)
  delegate_to: localhost
  # hide log to avoid exposing zowe_test_user and zowe_test_password
  no_log: True

- name: Wait for Desktop at {{zowe_zos_host}} port {{ zowe_zlux_port }} to be available
  uri:
    url: "https://{{ zowe_zos_host }}:{{ zowe_zlux_port }}"
    follow_redirects: all
    method: GET
    validate_certs: false
  register: _result
  until: _result.status == 200
  retries: "{{ wait_for_zowe_service_retries | int }}"
  delay: "{{ wait_for_zowe_service_delay | int }}"
  # if zowe_zos_host and zowe_external_domain_name are not same, zlux could be
  # started off z/OS and then we couldn't test right now
  when: zowe_zos_host == zowe_external_domain_name and (zowe_launch_components is none or zowe_launch_components == "" or "app-server" in zowe_launch_components)
  delegate_to: localhost

- name: Wait for being able to login to zLux
  uri:
    url: "https://{{ zowe_zos_host }}:{{ zowe_zlux_port }}/auth"
    follow_redirects: none
    method: POST
    body_format: json
    body: 
      username: "{{ zowe_test_user }}"
      password: "{{ zowe_test_password }}"
    validate_certs: false
    status_code:
    - 200
    - 204
  register: _result
  until: _result.status == 200
  retries: "{{ wait_for_zowe_service_retries | int }}"
  delay: "{{ wait_for_zowe_service_delay | int }}"
  # if zowe_zos_host and zowe_external_domain_name are not same, zlux could be
  # started off z/OS and then we couldn't test right now
  when: zowe_zos_host == zowe_external_domain_name and (zowe_launch_components is none or zowe_launch_components == "" or "app-server" in zowe_launch_components)
  delegate_to: localhost
  # hide log to avoid exposing zowe_test_user and zowe_test_password
  no_log: True

# - name: Wait for being able to login to ZSS
#   uri:
#     url: "{{ zowe_zss_https | ternary('https', 'http') }}://{{ zowe_zos_host }}:{{ zowe_zss_port }}/login"
#     follow_redirects: none
#     method: POST
#     body_format: json
#     body: 
#       username: "{{ zowe_test_user }}"
#       password: "{{ zowe_test_password }}"
#     validate_certs: false
#     status_code:
#     - 200
#   register: _result
#   until: _result.status == 200
#   retries: "{{ wait_for_zowe_service_retries | int }}"
#   delay: "{{ wait_for_zowe_service_delay | int }}"
#   delegate_to: localhost
#   when: zowe_zos_host == zowe_external_domain_name and (zowe_launch_components is none or zowe_launch_components == "" or "zss" in zowe_launch_components)
#   # hide log to avoid exposing zowe_test_user and zowe_test_password
#   no_log: True

# - name: Wait for ZSS at {{zowe_zos_host}} port {{ zowe_zss_port }} to be available
#   uri:
#     url: "{{ zowe_zss_https | ternary('https', 'http') }}://{{ zowe_zos_host }}:{{ zowe_zss_port }}/plugins"
#     follow_redirects: none
#     method: GET
#     validate_certs: false
#   register: _result
#   until: _result.status == 200
#   retries: "{{ wait_for_zowe_service_retries | int }}"
#   delay: "{{ wait_for_zowe_service_delay | int }}"
#   when: zowe_zos_host == zowe_external_domain_name and (zowe_launch_components is none or zowe_launch_components == "" or "zss" in zowe_launch_components)
#   delegate_to: localhost
