---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: discovery-pdb
  namespace: zowe
  labels:
    app.kubernetes.io/name: zowe
    app.kubernetes.io/instance: zowe
    app.kubernetes.io/version: "1.25.0"
    app.kubernetes.io/component: pdb
    app.kubernetes.io/managed-by: manual
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zowe
      app.kubernetes.io/instance: zowe
      app.kubernetes.io/component: discovery
