---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-api
  namespace: zowe
  labels:
    app.kubernetes.io/name: zowe
    app.kubernetes.io/instance: zowe
    app.kubernetes.io/version: 1.24.0
    app.kubernetes.io/component: jobs-api
    app.kubernetes.io/part-of: explorer-api
    app.kubernetes.io/managed-by: manual
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: zowe
      app.kubernetes.io/instance: zowe
      app.kubernetes.io/component: jobs-api
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zowe
        app.kubernetes.io/instance: zowe
        app.kubernetes.io/component: jobs-api
    spec:
      securityContext:
        runAsUser: 20000
        runAsGroup: 20000
        fsGroup: 20000
      serviceAccountName: zowe-sa
      volumes:
        - name: zowe-runtime
          emptyDir: {}
        - name: zowe-instance
          emptyDir: {}
        - name: zowe-config
          configMap:
            name: zowe-config
        - name: zowe-keystore
          projected:
            sources:
            - configMap:
                name: zowe-certificates-cm
            - secret:
                name: zowe-certificates-secret
        - name: zowe-workspace
          persistentVolumeClaim:
            claimName: zowe-workspace-pvc
      containers:
        - name: jobs-api
          image: zowe-docker-release.jfrog.io/ompzowe/jobs-api:latest-ubuntu
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - containerPort: 8545
              protocol: TCP
          command: ["/bin/bash", "-c"]
          args:
            - "/home/zowe/instance/bin/internal/run-zowe.sh"
          env:
            - name: ZWE_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","/home/zowe/runtime/bin/internal/container-prestop.sh"]
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: zowe-runtime
              mountPath: "/home/zowe/runtime"
            - name: zowe-instance
              mountPath: "/home/zowe/instance"
            - name: zowe-config
              mountPath: "/home/zowe/instance/instance.env"
              subPath: instance.env
              readOnly: true
            - name: zowe-keystore
              mountPath: "/home/zowe/keystore/"
              readOnly: true
            - name: zowe-workspace
              mountPath: "/home/zowe/instance/workspace"
      initContainers:
        - name: init-zowe
          # image: zowe-docker-release.jfrog.io/ompzowe/zowe-launch-scripts:latest
          image: zowe-docker-snapshot.jfrog.io/ompzowe/zowe-launch-scripts:1.24.0-ubuntu.staging
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: zowe-runtime
              mountPath: "/home/zowe/runtime"
            - name: zowe-instance
              mountPath: "/home/zowe/instance"
