name: build

on:
  # Triggers the workflow on push or pull request events but only for the staging branch
  pull_request:
    branches: [ staging ]

#  workflow_dispatch:
#    inputs:
#      dockerImage:
#        description: 'Please enter version number'     
#        required: true
#        default: 'warning'

jobs:
  build:
    name: Build
    runs-on: "ubuntu-18.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'zowe-docker-snapshot.jfrog.io/ompzowe/app-server:1.22.0'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'